[package]
name = "ruvo_cli"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true



[[bin]]
name = "ruvo"
path = "src/main.rs"