[test-groups]
# Tests with the serial integration test group will run serially, not concurrency.
serial-integration = { max-threads = 1 }

[profile.ci]
# Retry tests before failing them.
retries = { backoff = "exponential", count = 2, delay = "2s" }
# Do not cancel the test run on the first failure.
fail-fast = false
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"

# Running tests serially, not concurrency.
[[profile.ci.overrides]]
filter = 'test(serial_integration)'
test-group = 'serial-integration'

# save junit report
[profile.ci.junit]
path = "junit.xml"
