[package]
name = "ruvo_server"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[[bin]]
name = "ruvo_server"
path = "src/main.rs"

[dependencies]
ahash = "0.8.12"
dashmap = "6.1.0"
